# Generated by Django 2.2.7 on 2019-12-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlparser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='code_de_verification',
            field=models.TextField(blank=True, help_text='Ici on ajoute le code sql de verification.<br />Exemple: select * from table <br />Cela nous permet de voir si le candidat  a supprimer, modifier ou ajouté la colene  ', null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='type_de_requete',
            field=models.IntegerField(choices=[(1, 'Query'), (2, 'Mutation')], default=1, help_text='Ici on a deux type de reque: <br />Query pour les requete de type SELECT. <br />Mutation pour les requete de type UPDATE, ADD, DELETE'),
        ),
    ]
