# Generated by Django 2.2.7 on 2019-12-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlparser', '0002_exercices_codesql_depart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.AlterModelOptions(
            name='tests',
            options={'verbose_name': 'Questions', 'verbose_name_plural': 'Questionss'},
        ),
        migrations.AddField(
            model_name='tests',
            name='codesql_table',
            field=models.TextField(default='ok'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tests',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
