# Generated by Django 2.2.7 on 2019-12-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlparser', '0004_auto_20191203_1207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tests',
        ),
    ]
