# Generated by Django 2.2.7 on 2019-12-03 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqlparser', '0005_delete_tests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercices',
            old_name='codesql_depart',
            new_name='codesql_creation',
        ),
        migrations.RemoveField(
            model_name='exercices',
            name='codesql_reponse',
        ),
        migrations.RemoveField(
            model_name='exercices',
            name='point',
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('enonce', models.TextField()),
                ('codesql_depart', models.TextField()),
                ('codesql_reponse', models.TextField()),
                ('point', models.PositiveIntegerField()),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questexo', to='sqlparser.Exercices')),
            ],
            options={
                'verbose_name': 'Questions',
                'verbose_name_plural': 'Questionss',
            },
        ),
    ]
