# Generated by Django 2.2.7 on 2019-12-03 16:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlparser', '0006_auto_20191203_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercices',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
