# Generated by Django 2.2.7 on 2019-12-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlparser', '0007_auto_20191203_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercices',
            name='minidescription',
            field=models.TextField(null=True),
        ),
    ]
