# Generated by Django 2.2.7 on 2019-12-19 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Enonce',
                'verbose_name_plural': 'Enonces',
            },
        ),
        migrations.CreateModel(
            name='ValidationHtml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balise', models.CharField(help_text='Ex : p, h1, div, a, img, ... ', max_length=250)),
                ('attribue', models.CharField(help_text='Ex : class, id, href, src, target, ... ', max_length=250)),
                ('attribue_value', models.CharField(help_text='Ex : contenaire, app, http://nan.ci, __blank, ... ', max_length=250)),
                ('niveau', models.PositiveIntegerField(default=1, help_text='Ex: 1 si la verification se fait au premier niveau <br />2 Si la verification se fait au niveau 2, ')),
                ('many', models.BooleanField(default=False, help_text="Ex: Cocher si l'element se propose plusieur fois")),
                ('nombre', models.PositiveIntegerField(default=1, help_text="Le nombre de fois que l'element s'affiche")),
                ('enoncer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valideenoncer', to='editors.Enonce')),
            ],
            options={
                'verbose_name': 'ValidationHtml',
                'verbose_name_plural': 'ValidationHtmls',
            },
        ),
    ]
