# Generated by Django 2.2.7 on 2019-11-28 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationhtml',
            name='enoncer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valideenoncer', to='editors.Enonce'),
        ),
    ]
